defaults:
    - _self_
    - task@_global_: place_brick
    - override hydra/launcher: submitit_local

# task settings
task_name: place_brick 
seed: 3 # 0~4
device: cuda
gpu_id: 2
save_video: true
use_tb: False 

# train
episodes: 200
steps_per_episode: 2000
max_ep_len: 500 # < steps_per_episode
lr_actor: 3e-4 
lr_critic: 1e-3
train_v_iters: 80
save_freq: 10
gamma: 0.99 # gamma (float): Discount factor. (Always between 0 and 1.)
lam: 0.95 # lam (float): Lambda for GAE-Lambda. (Always between 0 and 1, close to 1)

# experiment
experiment: exp

# network
obs_dim: ??? # to be specified later
act_dim: ??? # to be specified later
hidden_dim_1: 512
hidden_dim_2: 256
hidden_dim_3: 128 

hydra:
  run:
    # dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
    # dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${task_name}
    dir: ./exp_local/${task_name}_seed_${seed}/${now:%Y.%m.%d}_${now:%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 4 
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
